In [1]:
# Eleven line Neural Network (annotated version!)
import numpy as np

In [2]:
# sigmoid function
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [3]:
# input dataset
X = np.array([ [0,0,1],
                 [0,1,1],
                 [1,0,1],
                 [1,1,1] ])

In [4]:
# output dataset
y = np.array([ [0,0,1,1] ]).T

In [12]:
# set random seed
np.random.seed(123)

In [13]:
# initialize weights randomly with mean 0
weights = 2*np.random.random((3,1)) - 1
weights

array([[ 0.39293837],
       [-0.42772133],
       [-0.54629709]])

In [14]:
for iter in xrange(5):
    
    print "\n\n---------ITERATION #{}-------------".format(iter)
    
     # forward prop
    l0 = X
    print "inputs:\n {}\n".format(l0)
    
    dp = np.dot(l0, weights) #ps
    
    print "weights:\n {}\n".format(weights)
    print "dot product results:\n {}\n".format(dp)
    l1 = nonlin(dp)
    
    print "l1 probability predictions (sigmoid):\n {}\n".format(l1)
    
    # how much did we miss?
    l1_error = y - l1
    
    print "y:\n {}\n\n l1_error:\n {}\n".format(y, l1_error)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    nl = nonlin(l1,True) #ps
    
    print "sigmoid derivative (update weight):\n {}\n".format(nl)
    
    l1_delta = l1_error * nl
    
    print "l1 delta (weighted error):\n {}\n".format(l1_delta)
    
    # update weights
    trans = l0.T #ps
    
    print "transpose of input weights:\n {}".format(trans)
    dp2 = np.dot(trans, l1_delta) #ps
    
    print "dot product of inputs and l1 delta:\n {}\n".format(dp2)
    
    print "pre-update weights:\n {}\n".format(weights)
    
    weights += np.dot(l0.T, l1_delta)
    
    print "post-update weights:\n {}\n".format(weights)



---------ITERATION #0-------------
inputs:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights:
 [[ 0.39293837]
 [-0.42772133]
 [-0.54629709]]

dot product results:
 [[-0.54629709]
 [-0.97401842]
 [-0.15335872]
 [-0.58108005]]

l1 probability predictions (sigmoid):
 [[ 0.36672394]
 [ 0.27408027]
 [ 0.46173529]
 [ 0.35868411]]

y:
 [[0]
 [0]
 [1]
 [1]]

 l1_error:
 [[-0.36672394]
 [-0.27408027]
 [ 0.53826471]
 [ 0.64131589]]

sigmoid derivative (update weight):
 [[ 0.23223749]
 [ 0.19896028]
 [ 0.24853581]
 [ 0.23002982]]

l1 delta (weighted error):
 [[-0.08516705]
 [-0.05453109]
 [ 0.13377806]
 [ 0.14752178]]

transpose of input weights:
 [[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]
dot product of inputs and l1 delta:
 [[ 0.28129984]
 [ 0.09299069]
 [ 0.1416017 ]]

pre-update weights:
 [[ 0.39293837]
 [-0.42772133]
 [-0.54629709]]

post-update weights:
 [[ 0.67423821]
 [-0.33473064]
 [-0.40469539]]



---------ITERATION #1-------------
inputs:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights:
 [[ 0.67

In [24]:
print "Output After Trainng"
print l1

Output After Trainng
[[ 0.00964731]
 [ 0.00785112]
 [ 0.99360033]
 [ 0.99213357]]
