In [8]:
# Eleven line Neural Network
import numpy as np

In [9]:
# sigmoid function
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [10]:
# input dataset
X = np.array([ [0,0,1],
                 [0,1,1],
                 [1,0,1],
                 [1,1,1] ])

In [11]:
# output dataset
y = np.array([ [0,0,1,1] ]).T

In [12]:
# set random seed
np.random.seed(1)

In [13]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

In [29]:
for iter in xrange(5):
    
    print "\n\n---------ITERATION #{}-------------".format(iter)
    
     # forward prop
    l0 = X
    print "inputs:\n {}\n".format(l0)
    
    dp = np.dot(l0, syn0) #ps
    
    print "weights:\n {}\n".format(syn0)
    print "dot product results:\n {}\n".format(dp)
    l1 = nonlin(dp)
    
    print "probability predictions (sigmoid):\n {}\n".format(l1)
    
    # how much did we miss?
    l1_error = y - l1
    
    print "y:\n {}\n\n l1_error:\n {}\n".format(y, l1_error)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    nl = nonlin(l1,True) #ps
    
    print "deriv portion:\n {}\n".format(nl)
    
    l1_delta = l1_error * nl
    
    print "l1 delta:\n {}\n".format(l1_delta)
    
    # update weights
    trans = l0.T #ps
    dp2 = np.dot(trans, l1_delta) #ps
    
    print "dot product of inputs and l1 delta:\n {}\n".format(dp2)
    
    print "pre-update weights:\n {}\n".format(syn0)
    
    syn0 += np.dot(l0.T, l1_delta)
    
    print "post-update weights:\n {}\n".format(syn0)



---------ITERATION #0-------------
inputs:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights:
 [[ 9.67657224]
 [-0.20783515]
 [-4.63143321]]

dot product results:
 [[-4.63143321]
 [-4.83926837]
 [ 5.04513903]
 [ 4.83730387]]

probability predictions (sigmoid):
 [[ 0.00964682]
 [ 0.00785072]
 [ 0.99360065]
 [ 0.99213396]]

y:
 [[0]
 [0]
 [1]
 [1]]

 l1_error:
 [[-0.00964682]
 [-0.00785072]
 [ 0.00639935]
 [ 0.00786604]]

deriv portion:
 [[ 0.00955376]
 [ 0.00778909]
 [ 0.0063584 ]
 [ 0.00780416]]

l1 delta:
 [[ -9.21634077e-05]
 [ -6.11499308e-05]
 [  4.06896096e-05]
 [  6.13878173e-05]]

dot product of inputs and l1 delta:
 [[  1.02077427e-04]
 [  2.37886518e-07]
 [ -5.12359116e-05]]

pre-update weights:
 [[ 9.67657224]
 [-0.20783515]
 [-4.63143321]]

post-update weights:
 [[ 9.67667432]
 [-0.20783491]
 [-4.63148445]]



---------ITERATION #1-------------
inputs:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights:
 [[ 9.67667432]
 [-0.20783491]
 [-4.63148445]]

dot product results:
 [[-4.63

In [24]:
print "Output After Trainng"
print l1

Output After Trainng
[[ 0.00964731]
 [ 0.00785112]
 [ 0.99360033]
 [ 0.99213357]]


In [28]:
np.random.random??

In [25]:
np.random.random((3,1))

array([[ 0.30233257],
       [ 0.14675589],
       [ 0.09233859]])