In [1]:
# 3 layer NN
import numpy as np

In [2]:
# sigmoid function
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [3]:
# input dataset
X = np.array([ [0,0,1],
                 [0,1,1],
                 [1,0,1],
                 [1,1,1] ])

In [4]:
# output dataset
y = np.array([ [0,1,1,0] ]).T

In [5]:
np.random.seed(1)
# randomly initialize weights with mean 0
weights0 = 2*np.random.random((3,4)) - 1
weights1 = 2*np.random.random((4,1)) - 1

In [6]:
weights0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [7]:
weights1

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [8]:
for i in xrange(3):
    
    print "\n\n---------ITERATION #{}-------------".format(i)
    
    # Feed forard through layers 0, 1, and 2
    l0 = X
    
    print "inputs:\n {}\n".format(l0)
    
    ### Going to layer 1 predictions
    l1_dot_product = np.dot(l0,weights0)
    print "l1 dot product:\n {}\n".format(l1_dot_product)
    
    l1_sigmoid = nonlin(l1_dot_product)
    print "l1_sigmoid:\n {}\n".format(l1_sigmoid)
    
    l1 = nonlin(np.dot(l0,weights0))
    
    ### Going to layer 2 predictions
    
    l2_dot_product = np.dot(l1,weights1)
    print "l2 dot product:\n {}\n".format(l2_dot_product)
    
    l2_sigmoid = nonlin(l2_dot_product)
    print "l2_sigmoid:\n {}\n".format(l2_sigmoid)
    
    l2 = nonlin(np.dot(l1,weights1))
    
    # how much did we miss the target value?
    l2_error = y - l2
    
    print "y:\n {}\n".format(y)
    print "l2:\n {}\n".format(l2)
    print "l2_error:\n {}\n".format(l2_error)
    
    if (i% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error))) + "\n"
        
    # in what direction is the target value?
    # were we really sure? If so, don't change too much.
    l2_sig_deriv = nonlin(l2, deriv=True)
    print "l2 sigmoid derivative:\n {}\n".format(l2_sig_deriv)
    
    l2_delta = l2_error * nonlin(l2, deriv=True)
    print "l2_delta (weighted error):\n {}\n".format(l2_delta)
    
    # how much did each l1 value contribute to the l2 error
    # according to the weights?
    print "transpose weights1:\n {}\n".format(weights1.T)
    
    l1_error = l2_delta.dot(weights1.T)
    print "l1_error (l2_delta dot weights1):\n {}\n".format(l1_error)
    
    # in what direction is the target value?
    # were we really sure? If so, don't change too much.
    
    l1_sig_deriv = nonlin(l1, deriv=True)
    print "l1 sigmoid derivative:\n {}\n".format(l1_sig_deriv)
    
    l1_delta = l1_error * nonlin(l1, deriv=True)
    print "l1_delta (weighted error):\n {}\n".format(l1_delta)
    
    print"Pre-update weight0:\n {}\nweight 1:\n {}\n".format(weights0,
                                                      weights1)
    weights1 += l1.T.dot(l2_delta)
    weights0 += l0.T.dot(l1_delta)
    
    print"Post-update weight0:\n {}\nweight 1:\n {}\n".format(weights0,
                                                      weights1)



---------ITERATION #0-------------
inputs:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

l1 dot product:
 [[-0.20646505  0.07763347 -0.16161097  0.370439  ]
 [-0.91295327 -0.73768934 -0.78909055  0.06156045]
 [-0.37242104  0.51828245 -1.16138222 -0.02489585]
 [-1.07890926 -0.29704036 -1.7888618  -0.3337744 ]]

l1_sigmoid:
 [[ 0.44856632  0.51939863  0.45968497  0.59156505]
 [ 0.28639589  0.32350963  0.31236398  0.51538526]
 [ 0.40795614  0.62674606  0.23841622  0.49377636]
 [ 0.25371248  0.42628115  0.14321233  0.41732254]]

l2 dot product:
 [[-0.10517857]
 [-0.04417936]
 [ 0.17581491]
 [ 0.17931239]]

l2_sigmoid:
 [[ 0.47372957]
 [ 0.48895696]
 [ 0.54384086]
 [ 0.54470837]]

y:
 [[0]
 [1]
 [1]
 [0]]

l2:
 [[ 0.47372957]
 [ 0.48895696]
 [ 0.54384086]
 [ 0.54470837]]

l2_error:
 [[-0.47372957]
 [ 0.51104304]
 [ 0.45615914]
 [-0.54470837]]

Error:0.496410031903

l2 sigmoid derivative:
 [[ 0.24930986]
 [ 0.24987805]
 [ 0.24807798]
 [ 0.24800116]]

l2_delta (weighted error):
 [[-0.11810546]
 [ 