In [1]:
# 3 layer NN
import numpy as np

In [2]:
# sigmoid function
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [3]:
# input dataset
X = np.array([ [0,0,1],
                 [0,1,1],
                 [1,0,1],
                 [1,1,1] ])

In [4]:
# output dataset
y = np.array([ [0,1,1,0] ]).T

In [6]:
np.random.seed(1)
# randomly initialize weights with mean 0
weights0 = 2*np.random.random((3,4)) - 1
weights1 = 2*np.random.random((4,1)) - 1

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [7]:
weights0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [8]:
weights1

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [ ]:
for i in xrange(60000):
    
    print "\n\n---------ITERATION #{}-------------".format(i)
    
    # Feed forard through layers 0, 1, and 2
    l0 = X
    
    print "inputs: {}".format(l0)
    
    ### Going to layer 1 predictions
    l1_dot_product = np.dot(l0,weights0)
    print "l1 dot product: {}".format(l1_dot_product)
    
    l1_sigmoid = nonlin(l1_dot_product)
    print "l1_sigmoid: {}".format(l1_sigmoid)
    
    l1 = nonlin(np.dot(l0,weights0))
    
    ### Going to layer 2 predictions
    
    l2_dot_product = np.dot(l1,weights1)
    print "l2 dot product: {}".format(l2_dot_product)
    
    l2_sigmoid = nonlin(l2_dot_product)
    print "l2_sigmoid: {}".format(l2_sigmoid)
    
    l2 = nonlin(np.dot(l1,weights1))
    
    # how much did we miss the target value?
    l2_error = y - l2
    
    print "y: {}".format(y)
    print "l2: {}".format(l2)
    print "l2_error: {}".format(l2_error)
    
    if (i% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))
        
    # in what direction is the target value?
    # were we really sure? If so, don't change too much.
    l2_delta = l2_error * nonlin(l2, deriv=True)
    
    # how much did each l1 value contribute to the l2 error
    # according to the weights?
    l1_error = l2_delta.dot(weights1.T)
    
    # in what direction is the target value?
    # were we really sure? If so, don't change too much.
    l1_delta = l1_error * nonlin(l1, deriv=True)
    
    weights1 += l1.T.dot(l2_delta)
    weights0 += l0.T.dot(l1_delta)